### ISSUE TITLE
Error in runtime "ReferenceError: process is not defined".

### ISSUE THREAD

**Issue by c4lliope** [taybenlor/runno#198] opened 2022-04-25 23:57 UTC
I am running Ruby in a `<runno-run>...</>`, using:

```
import { defineElements } from '@runno/runtime'

window.process = window.process || {
  platform: null,
  browser: true,
  env: {
    NODE_DEBUG: false,
  }
};

defineElements()
```
... as described in #183 .

Regardless, I am experiencing the error,
`Error in runtime "ReferenceError: process is not defined".`

- - -

As a second problem, I'm seeking an approach for running code from a JS function,
rather than a Web Component label, `<runno-run>...</>` -
something more like: `Runno.run('ruby', `p "Runner #0"`).then((...) => console.log(...))`
Any ideas?

**Comment by c4lliope** [comment] 2022-04-25 23:59
You can access an example here: [moped](https://moped.assembled.app/).

**Comment by taybenlor** [comment] 2022-04-26 07:28
Hi @c4lliope thanks for the report! This looks like it's a duplicate of #183

**Closed by taybenlor** 2022-04-26 07:28 UTC

**Comment by taybenlor** [comment] 2022-04-26 07:30
As for your second issue. The best way to do that is using `headlessRunCommand` see the documentation here: https://runno.dev/#component-helpers

Could you please use the discussion board if you have any questions in future, thanks!

**Comment by c4lliope** [comment] 2022-04-26 14:35
Ah, sure - thanks for your quick reply and help!

**Comment by c4lliope** [comment] 2022-04-26 15:21
As clarification, my problem had been declaring the `window.process` fallback inside of my imported `application.js` file;
you likely need this defined before the `import { defineElements } ...` call.

When I placed this fallback inside my page's `<head>...</head>` section,
the library picked up the `process` I defined.

So make sure you place this inside your `<head>`, or else before you load (import) `runno`:

```
<head>
  ...
  <script>
  window.process = window.process || {
    platform: null,
    browser: true,
    env: {
      NODE_DEBUG: false,
    }
  };
  </script>
</head>
```

**Comment by taybenlor** [comment] 2022-04-27 12:46
Thanks for explaining!
